import { useLayoutEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, ChevronRight, Instagram, Menu, Search, ShoppingBag, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useCart } from "@/contexts/CartContext";
import { formatMoney } from "@/lib/format";
import { startLogin } from "@/const";
import gsap from "gsap";
import type { Product } from "@shared/commerce/types";

const categories = ["Todos", "Camisetas", "Quimonos", "Bolsas", "Canecas", "Souvenires"];

function ProductCard({ product }: { product: Product }) {
  const { addItem, loading } = useCart();
  const variant = product.variants[0];
  const image = product.images[0];
  const secondImage = product.images[1];
  const sizeOption = product.options.find((option) => /tamanho|size/i.test(option.name));

  return (
    <article className="group product-card min-w-0">
      <a href={`/produto/${product.handle}`} className="relative block aspect-[3/4] overflow-hidden bg-[#e9e5df]" aria-label={`Ver ${product.title}`}>
        {image ? <><img src={image.url} alt={image.altText ?? product.title} className={`h-full w-full object-cover transition duration-700 ease-out ${secondImage ? "group-hover:opacity-0" : "group-hover:scale-[1.03]"}`} />{secondImage && <img src={secondImage.url} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-0 transition duration-700 ease-out group-hover:scale-[1.03] group-hover:opacity-100" />}</> : <div className="flex h-full items-center justify-center px-8 text-center text-xs uppercase tracking-[0.18em] text-[#67625b]">Imagem em preparação</div>}
        <span className="absolute left-3 top-3 bg-[#f5f2ed] px-2 py-1 text-[10px] uppercase tracking-[0.18em] text-[#24211f]">{product.productType || "Arte Que Veste"}</span>
        <button aria-label={`Adicionar ${product.title} ao carrinho`} disabled={!variant?.availableForSale || loading} onClick={(event) => { event.preventDefault(); if (variant) addItem(variant.id); }} className="absolute bottom-3 left-3 right-3 translate-y-2 bg-[#24211f] py-3 text-xs uppercase tracking-[0.16em] text-[#f5f2ed] opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100 disabled:cursor-not-allowed disabled:bg-[#67625b] md:block">{variant?.availableForSale ? "Adicionar ao carrinho" : "Indisponível"}</button>
      </a>
      <div className="flex items-start justify-between gap-4 pt-3"><div className="min-w-0"><h3 className="truncate text-sm font-medium text-[#24211f]">{product.title}</h3><p className="mt-1 text-xs uppercase tracking-[0.12em] text-[#817970]">{product.productType || "Peça Arte Que Veste"}</p>{sizeOption && <p className="mt-2 text-[10px] uppercase tracking-[0.12em] text-[#817970]">Tamanhos: {sizeOption.values.join(" · ")}</p>}<p className="mt-2 text-[10px] uppercase tracking-[0.12em] text-[#23867f]">{product.variants.some((item) => item.availableForSale) ? "Disponível" : "Esgotado"}</p></div><span className="shrink-0 text-sm font-medium text-[#24211f]">{formatMoney(product.priceRange.min)}</span></div>
    </article>
  );
}

function CartDrawer() {
  const { cart, isOpen, closeCart, updateQuantity, removeItem, proceedToCheckout, loading } = useCart();
  if (!isOpen) return null;
  return <div className="fixed inset-0 z-50 bg-[#24211f]/45" onClick={closeCart}><aside className="absolute right-0 top-0 flex h-full w-full max-w-[440px] flex-col bg-[#f5f2ed] p-5 shadow-2xl md:p-7" onClick={(event) => event.stopPropagation()}>
    <div className="flex items-start justify-between border-b border-[#d5cec5] pb-5"><div><p className="text-[10px] uppercase tracking-[0.22em] text-[#817970]">Sua seleção</p><h2 className="mt-2 font-display text-3xl text-[#24211f]">Carrinho</h2></div><button aria-label="Fechar carrinho" onClick={closeCart} className="p-2 text-[#24211f] hover:bg-[#e9e5df]"><X size={20} /></button></div>
    <div className="flex-1 space-y-5 overflow-y-auto py-6">{!cart?.items.length ? <div className="border border-dashed border-[#bdb4aa] p-5 text-sm leading-relaxed text-[#67625b]">Seu carrinho está vazio. Explore as peças da coleção.</div> : cart.items.map((item) => <div key={item.lineId} className="flex gap-3 border-b border-[#d5cec5] pb-5">{item.image ? <img src={item.image.url} alt={item.image.altText ?? item.productTitle} className="h-24 w-[76px] object-cover" /> : <div className="h-24 w-[76px] bg-[#e9e5df]" />}<div className="min-w-0 flex-1"><h3 className="text-sm font-medium text-[#24211f]">{item.productTitle}</h3><p className="mt-1 text-sm text-[#67625b]">{formatMoney(item.unitPrice)}</p><div className="mt-4 flex items-center gap-2"><button className="h-7 w-7 border border-[#bdb4aa]" onClick={() => updateQuantity(item.lineId, item.quantity - 1)} disabled={loading}>−</button><span className="w-5 text-center text-sm">{item.quantity}</span><button className="h-7 w-7 border border-[#bdb4aa]" onClick={() => updateQuantity(item.lineId, item.quantity + 1)} disabled={loading}>+</button><button className="ml-2 text-[10px] uppercase tracking-[0.14em] text-[#817970]" onClick={() => removeItem(item.lineId)}>Remover</button></div></div></div>)}</div>
    <div className="space-y-4 border-t border-[#d5cec5] pt-5"><div className="flex justify-between text-sm"><span>Subtotal</span><strong>{cart ? formatMoney(cart.subtotal) : "R$ 0,00"}</strong></div><p className="text-xs leading-relaxed text-[#817970]">Frete, prazo e formas de pagamento são calculados no checkout.</p><Button className="h-12 w-full rounded-none bg-[#24211f] text-xs uppercase tracking-[0.16em] text-[#f5f2ed] hover:bg-[#23867f]" disabled={!cart?.itemCount || loading} onClick={proceedToCheckout}>Finalizar compra <ArrowRight size={15} /></Button></div>
  </aside></div>;
}

export default function Home() {
  const [category, setCategory] = useState("Todos");
  const [menuOpen, setMenuOpen] = useState(false);
  const [consentVisible, setConsentVisible] = useState(() => localStorage.getItem("artequeveste-consent") === null);
  const { itemCount, openCart } = useCart();
  const { data: products = [], isLoading } = trpc.commerce.products.list.useQuery({ first: 24 });
  const pageRef = useRef<HTMLDivElement | null>(null);
  const filtered = useMemo(() => category === "Todos" ? products : products.filter((product) => (product.productType ?? "").toLowerCase().includes(category.toLowerCase().slice(0, -1))), [category, products]);

  useLayoutEffect(() => {
    if (!pageRef.current || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const ctx = gsap.context(() => { gsap.from(".fashion-hero-copy > *", { y: 28, opacity: 0, duration: 0.8, stagger: 0.07, ease: "power3.out" }); gsap.from(".fashion-hero-image", { scale: 1.06, opacity: 0, duration: 1.15, ease: "power3.out" }); gsap.from(".product-card", { y: 18, opacity: 0, duration: 0.65, stagger: 0.06, ease: "power3.out", delay: 0.25 }); }, pageRef);
    return () => ctx.revert();
  }, [products.length]);

  return <div ref={pageRef} className="min-h-screen bg-[#f5f2ed] text-[#24211f]">
    <div className="bg-[#24211f] px-4 py-2 text-center text-[10px] uppercase tracking-[0.2em] text-[#f5f2ed]">Frete calculado no checkout · Enviamos para todo o Brasil</div>
    <header className="sticky top-0 z-30 border-b border-[#d5cec5] bg-[#f5f2ed]/95 backdrop-blur-md"><div className="container flex h-[72px] items-center justify-between gap-6"><button aria-label="Abrir menu" className="md:hidden" onClick={() => setMenuOpen((value) => !value)}>{menuOpen ? <X size={19} /> : <Menu size={19} />}</button><a href="#inicio" className="font-display text-[21px] font-semibold tracking-[-0.06em]">ARTE QUE VESTE</a><nav className={`${menuOpen ? "absolute left-0 right-0 top-[72px] flex border-b border-[#d5cec5] bg-[#f5f2ed] p-5" : "hidden"} flex-col gap-5 text-[11px] uppercase tracking-[0.16em] md:static md:flex md:flex-row md:items-center md:gap-7 md:border-0 md:bg-transparent md:p-0`}><a href="#novidades" onClick={() => setMenuOpen(false)} className="hover:text-[#23867f]">Novidades</a><a href="#colecao" onClick={() => setMenuOpen(false)} className="hover:text-[#23867f]">Roupas</a><a href="#colecao" onClick={() => setMenuOpen(false)} className="hover:text-[#23867f]">Acessórios</a><a href="#sobre" onClick={() => setMenuOpen(false)} className="hover:text-[#23867f]">A marca</a></nav><div className="flex items-center gap-1"><button aria-label="Buscar" className="hidden p-2 hover:text-[#23867f] sm:block"><Search size={18} /></button><button aria-label="Entrar na conta" onClick={() => startLogin()} className="hidden px-2 py-2 text-[10px] uppercase tracking-[0.16em] hover:text-[#23867f] sm:block">Entrar</button><button aria-label="Abrir carrinho" onClick={openCart} className="relative p-2 hover:text-[#23867f]"><ShoppingBag size={19} />{itemCount > 0 && <span className="absolute -right-1 -top-1 flex h-[17px] min-w-[17px] items-center justify-center bg-[#23867f] px-1 text-[9px] text-white">{itemCount}</span>}</button></div></div></header>
    <main>
      <section id="inicio" className="container grid min-h-[min(720px,calc(100vh-96px))] gap-8 py-8 md:grid-cols-[0.86fr_1.14fr] md:items-stretch md:py-10"><div className="fashion-hero-copy flex flex-col justify-between py-8 md:py-12"><div><p className="mb-8 text-[10px] uppercase tracking-[0.24em] text-[#817970]">Coleção 01 · Sergipe / Brasil</p><h1 className="max-w-[9ch] font-display text-[clamp(3.8rem,8vw,7.4rem)] font-medium leading-[0.86] tracking-[-0.085em]">Vestir<br />memória.</h1><p className="mt-8 max-w-sm text-base leading-relaxed text-[#67625b]">Peças autorais que aproximam a xilogravura nordestina do vestir contemporâneo.</p><a href="#novidades" className="mt-9 inline-flex items-center gap-3 text-[11px] uppercase tracking-[0.18em] underline decoration-[#23867f] underline-offset-8 hover:text-[#23867f]">Ver novidades <ArrowRight size={15} /></a></div><div className="mt-12 flex items-center gap-4 text-[10px] uppercase tracking-[0.18em] text-[#817970]"><span className="h-px w-10 bg-[#23867f]" /> Feito para circular</div></div><div className="fashion-hero-image relative min-h-[470px] overflow-hidden bg-[#23867f] [background-image:repeating-linear-gradient(135deg,rgba(245,242,237,.07)_0_1px,transparent_1px_9px),linear-gradient(135deg,#23867f,#176b66)] md:min-h-0"><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(36,33,31,.2),transparent_45%,rgba(36,33,31,.38))]" /><div className="absolute inset-7 border border-[#f5f2ed]/60 md:inset-10" /><div className="absolute bottom-8 left-8 right-8 flex items-end justify-between text-[#f5f2ed] md:bottom-12 md:left-12 md:right-12"><div><p className="text-[10px] uppercase tracking-[0.24em]">Arte Que Veste</p><p className="mt-3 font-display text-4xl leading-[0.9] tracking-[-0.06em] md:text-6xl">Da mão,<br />do território.</p></div><span className="flex h-14 w-14 items-center justify-center rounded-full border border-[#e4a83b] text-center text-[9px] uppercase leading-tight tracking-[0.12em] text-[#e4a83b]">01<br />SE</span></div></div></section>
      <section id="novidades" className="border-y border-[#d5cec5] bg-[#ebe6df] py-14 md:py-20"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-[#817970]">O que chegou agora</p><h2 className="mt-3 font-display text-4xl tracking-[-0.06em] md:text-6xl">Novidades</h2></div><a href="#colecao" className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] hover:text-[#23867f]">Ver tudo <ChevronRight size={14} /></a></div><div className="mt-9 grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{isLoading ? Array.from({ length: 4 }).map((_, index) => <div key={index} className="aspect-[3/4] animate-pulse bg-[#d8d0c7]" />) : products.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>
      <section id="colecao" className="container py-16 md:py-24"><div className="flex flex-col justify-between gap-6 border-b border-[#d5cec5] pb-7 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-[#817970]">Comprar por categoria</p><h2 className="mt-3 font-display text-4xl tracking-[-0.06em] md:text-5xl">A coleção</h2></div><div className="flex flex-wrap gap-x-5 gap-y-3">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`text-[10px] uppercase tracking-[0.15em] ${category === item ? "border-b border-[#23867f] pb-1 text-[#23867f]" : "text-[#817970] hover:text-[#24211f]"}`}>{item}</button>)}</div></div><div className="mt-10 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{isLoading ? Array.from({ length: 8 }).map((_, index) => <div key={index} className="aspect-[3/4] animate-pulse bg-[#e9e5df]" />) : filtered.length ? filtered.map((product) => <ProductCard key={product.id} product={product} />) : <div className="col-span-full border border-dashed border-[#bdb4aa] p-12 text-center"><h3 className="font-display text-3xl tracking-[-0.05em]">A próxima tiragem está sendo preparada.</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-relaxed text-[#67625b]">Em breve, novas peças autorais chegam para vestir a memória, o território e a imaginação.</p></div>}</div></section>
      <section id="sobre" className="bg-[#24211f] py-16 text-[#f5f2ed] md:py-24"><div className="container grid gap-12 md:grid-cols-[0.8fr_1.2fr] md:items-end"><div><p className="text-[10px] uppercase tracking-[0.22em] text-[#e4a83b]">A marca</p><h2 className="mt-4 max-w-md font-display text-5xl leading-[0.9] tracking-[-0.07em] md:text-7xl">Uma imagem também pode ser uma memória.</h2></div><div className="max-w-xl space-y-5 text-base leading-relaxed text-[#c8c0b7]"><p>A Arte Que Veste aproxima a força gráfica da xilogravura nordestina do cotidiano, criando peças para usar, circular e iniciar novas conversas.</p><p>O projeto se relaciona ao trabalho do Mestre Nivaldo Oliveira, em São Cristóvão/SE. Cada referência deve ser apresentada com contexto, respeito e verdade.</p><a href="#inicio" className="inline-flex items-center gap-3 pt-4 text-[10px] uppercase tracking-[0.18em] text-[#f5f2ed] underline decoration-[#e4a83b] underline-offset-8">Conheça o universo <ArrowRight size={15} /></a></div></div></section>
      <section className="border-b border-[#d5cec5] bg-[#f5f2ed] py-12"><div className="container grid gap-8 md:grid-cols-3"><div><p className="text-[10px] uppercase tracking-[0.2em] text-[#817970]">Compra simples</p><h3 className="mt-2 font-display text-2xl tracking-[-0.04em]">Pagamento seguro</h3><p className="mt-2 text-sm leading-relaxed text-[#67625b]">O checkout é finalizado em ambiente protegido do provedor de pagamento.</p></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-[#817970]">Brasil inteiro</p><h3 className="mt-2 font-display text-2xl tracking-[-0.04em]">Envio calculado</h3><p className="mt-2 text-sm leading-relaxed text-[#67625b]">Frete e prazo aparecem conforme o CEP e a modalidade escolhida.</p></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-[#817970]">Com cuidado</p><h3 className="mt-2 font-display text-2xl tracking-[-0.04em]">Atendimento próximo</h3><p className="mt-2 text-sm leading-relaxed text-[#67625b]">Trocas e pedidos recebem orientação pelo canal oficial da marca.</p></div></div></section>
    </main>
    {consentVisible && <div role="dialog" aria-label="Preferências de privacidade" className="fixed inset-x-4 bottom-4 z-40 border border-[#bdb4aa] bg-[#f5f2ed] p-5 shadow-2xl md:left-auto md:max-w-md"><p className="text-sm font-semibold">Sua privacidade importa</p><p className="mt-2 text-xs leading-relaxed text-[#67625b]">Usamos apenas o necessário para a loja funcionar. Analytics e marketing permanecem desativados até sua escolha.</p><div className="mt-4 flex gap-2"><button className="bg-[#24211f] px-4 py-2 text-[10px] uppercase tracking-[0.12em] text-[#f5f2ed]" onClick={() => { localStorage.setItem("artequeveste-consent", "essential"); setConsentVisible(false); }}>Somente essenciais</button><button className="border border-[#bdb4aa] px-4 py-2 text-[10px] uppercase tracking-[0.12em]" onClick={() => { localStorage.setItem("artequeveste-consent", "all"); setConsentVisible(false); }}>Aceitar tudo</button></div></div>}
    <footer className="bg-[#24211f] py-10 text-[#f5f2ed]"><div className="container flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="font-display text-2xl tracking-[-0.05em]">ARTE QUE VESTE</p><p className="mt-3 text-sm text-[#a9a097]">Arte para vestir, usar e levar consigo.</p></div><div className="flex items-center gap-4 text-[#a9a097]"><Instagram size={16} /><span className="text-[10px] uppercase tracking-[0.16em]">© 2026 Arte Que Veste</span></div><p className="text-[10px] text-[#817970] md:text-right">Conceito e identidade digital por Pedro Belentani</p></div></footer>
    <CartDrawer />
  </div>;
}
